# Generated by Django 3.2.8 on 2021-11-05 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sool',
            name='star_rating',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_rating', models.IntegerField()),
                ('image', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('sool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sool_review', to='main.sool')),
            ],
        ),
    ]
