# Generated by Django 3.2.8 on 2021-11-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211105_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sool',
            name='sool_image',
            field=models.ImageField(blank=True, upload_to='info_image'),
        ),
    ]
