# Generated by Django 3.2.8 on 2021-11-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='title', max_length=50),
        ),
    ]
