# Generated by Django 3.2.8 on 2021-11-10 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_review_image'),
        ('main', '0004_review_title'),
    ]

    operations = [
    ]
