# Generated by Django 3.2.8 on 2021-11-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_0004_alter_review_image_0004_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sool',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
