# Generated by Django 3.2.7 on 2021-11-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sool_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='sool',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
