# Generated by Django 3.2.7 on 2021-11-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sool_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sool',
            name='carbonic',
            field=models.SmallIntegerField(null=True),
        ),
    ]
