export const GET_RECOMMENDATION_LIST = 'GET_RECOMMENDATION_LIST';
export const GET_REVIEW_LIST = 'GET_REVIEW_LIST';
export const GET_REVIEW = 'GET_REVIEW';
export const POST_REVIEW = 'POST_REVIEW';
export const GET_TEST_RESULT = 'GET_TEST_RESULT';
export const GET_ALCOHOL_INFO = 'GET_ALCOHOL_INFO';
